# Generated by Django 2.0.3 on 2018-04-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerServiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=100, verbose_name='docker下的服务名字')),
                ('mappedPort', models.IntegerField(blank=True, null=True, verbose_name='映射的端口名字')),
                ('serviceStatus', models.BooleanField(verbose_name='服务运行的状态')),
                ('comment', models.CharField(max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': 'docker 服务状态',
                'ordering': ['serviceName'],
            },
        ),
    ]
