# Generated by Django 2.0.3 on 2018-04-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_dockerservicelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerservicelist',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
