# Generated by Django 2.0.3 on 2018-04-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180411_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerservicelist',
            name='mappedPort',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='映射的端口名字'),
        ),
        migrations.AlterField(
            model_name='dockerservicelist',
            name='serviceStatus',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='服务运行的状态'),
        ),
    ]
