# Generated by Django 2.0.3 on 2018-04-12 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180411_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50, verbose_name='部门名字')),
            ],
            options={
                'verbose_name_plural': '部门名字',
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='VoteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.CharField(max_length=30, verbose_name='投票人的名字')),
                ('voter_ip', models.GenericIPAddressField(verbose_name='投票者的IP')),
            ],
            options={
                'verbose_name_plural': '投票数据',
                'ordering': ['voter'],
            },
        ),
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OptionName', models.CharField(max_length=100, verbose_name='投票选项')),
                ('belongToDepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Department')),
            ],
            options={
                'verbose_name_plural': '投票选项',
                'ordering': ['OptionName'],
            },
        ),
        migrations.AddField(
            model_name='votedata',
            name='VoteOption_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.VoteOption'),
        ),
        migrations.AddField(
            model_name='votedata',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Department'),
        ),
    ]
