# Generated by Django 2.0.3 on 2018-04-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20180412_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱地址')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
            ],
        ),
    ]
