# Generated by Django 2.0.3 on 2018-04-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_logaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logaccount',
            options={'ordering': ['-email'], 'verbose_name_plural': '登陆名和密码'},
        ),
        migrations.AddField(
            model_name='dockerservicelist',
            name='isInSwarm',
            field=models.BooleanField(default=False, verbose_name='是否存在于swarm集群中'),
        ),
    ]
