# Generated by Django 2.0.3 on 2018-04-17 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20180413_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='OStype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OS_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='操作系统名字')),
            ],
            options={
                'verbose_name_plural': '操作系统名',
                'ordering': ['-OS_name'],
            },
        ),
        migrations.AddField(
            model_name='ipinterface',
            name='domain_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='ipinterface',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='ipinterface',
            name='OS_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.OStype'),
        ),
    ]
