# Generated by Django 2.0.3 on 2018-04-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20180417_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipinterface',
            name='especily',
            field=models.BooleanField(default=0, verbose_name='是否是特殊IP'),
        ),
    ]
