# Generated by Django 2.0.3 on 2018-04-18 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20180417_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=20, verbose_name='监控端口')),
                ('service_name', models.CharField(max_length=200, verbose_name='监控的服务名')),
                ('MonitorIP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.IpInterface')),
            ],
        ),
    ]
