# Generated by Django 2.0.5 on 2018-05-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_monitorservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='添加快照任务的时间')),
                ('applicationIp', models.GenericIPAddressField(verbose_name='对应的虚拟机的ip')),
                ('frequency', models.CharField(blank=True, max_length=50, null=True, verbose_name='快照备份的频率')),
            ],
            options={
                'verbose_name_plural': '定时的快照',
                'ordering': ['-applicationIp'],
            },
        ),
        migrations.AlterModelOptions(
            name='monitorservice',
            options={'ordering': ['-service_name'], 'verbose_name_plural': '监控的服务'},
        ),
    ]
