# Generated by Django 2.0.5 on 2018-06-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20180606_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshottask',
            name='interval',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='间隔时间每x'),
        ),
        migrations.AddField(
            model_name='snapshottask',
            name='snap_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='具体任务的时间'),
        ),
        migrations.AddField(
            model_name='snapshottask',
            name='week_day',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='星期几'),
        ),
    ]
