# Generated by Django 2.0.5 on 2018-06-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20180606_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshottask',
            name='timing_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='计时单位'),
        ),
        migrations.AlterField(
            model_name='snapshottask',
            name='snap_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='在每个具体任务的时间'),
        ),
        migrations.AlterField(
            model_name='snapshottask',
            name='week_day',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='在每个星期几'),
        ),
    ]
