# Generated by Django 2.0.5 on 2018-06-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20180606_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshottask',
            name='interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='间隔时间每x'),
        ),
        migrations.AlterField(
            model_name='snapshottask',
            name='snap_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='在每个具体任务的时间'),
        ),
    ]
